name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Docker Hub
      run: |
        chmod +x src/scripts/deploy.sh
        ./src/scripts/deploy.sh
        
    - name: Create deploy info
      run: |
        echo "Image: $DOCKERHUB_USERNAME/penguin-classifier-withDB" > docker-image-info.txt
        echo "Version: $(git describe --tags --always || echo 'latest')" >> docker-image-info.txt
        echo "Timestamp: $(date +%Y%m%d%H%M%S)" >> docker-image-info.txt
        
    - name: Upload deploy info
      uses: actions/upload-artifact@v4
      with:
        name: deploy-info
        path: docker-image-info.txt